pipeline {
    agent any // build-agent
    stages {
        stage('stage1') {
            steps {
                echo 'Hello World A1'
            }
        }
        stage('Stage2') {
            steps {
                echo 'Hello World A2'
            }
        }
    }
}
